name: Deploy Lab 07

on:
  push:
    branches: [main]
    paths:
      - 'web-components/lab07/**'
      - 'web-components/shared/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp -r web-components/lab07/* deploy/
          if [ -d "web-components/shared" ]; then
            cp -r web-components/shared deploy/shared
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: wxfreekj/lab07-student
          publish_branch: main
          publish_dir: ./deploy
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
